apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: python-ywenbyph-gitops
  description: This is GitOps manifest for python-ywenbyph   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: tssc/gitops=python-ywenbyph
    backstage.io/kubernetes-id: python-ywenbyph 
    backstage.io/techdocs-ref: dir:. 
    github.com/project-slug: rhtap-test-organization-jk/python-ywenbyph-gitops
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:python-ywenbyph
